// Developer Express Code Central Example:
// How to implement a custom LookUpEdit supporting Server Mode
// 
// The current LookUpEdit version does not allow using Server Mode datasources.
// This example demonstrates how to create a custom editor that allows using them.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4560

// Developer Express Code Central Example:
// How to implement a custom LookUpEdit supporting Server Mode
// 
// The current LookUpEdit version does not allow using Server Mode datasources.
// This example demonstrates how to create a custom editor that allows using them.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4560

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXGridSample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
